name: Shell Comands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: multiline script
        run: |
         # node -v
         # npm -v
          ps -ef
          pwd
          uname -a
          echo "Leandro Nunes"
          date
          echo "teste criacao de arquivo" > arquivoteste.txt
          cat arquivoteste.txt
          date

        - uses: nashmaniac/create-issue-action@v1.1
          if: ${{ failure() }} # only run when this job is failed.
          name: Create Issue Action
          with:
            title: Linter Failed
            token: ${{secrets.GITHUB_TOKEN}}
            assignees: ${{github.actor}}
            labels: refactoring-needed, help needed
            body: Workflow failed for commit ${{github.sha}}
